extends: ['eslint:recommended', 'plugin:react/recommended']
env:
  browser: true
  es6: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
